- name: install and run the nginx
  hosts: web
  tasks:
  - name: installing the nginx
    ansible.builtin.package:
      name: nginx
      state: present
 
  - name: starting the service
    ansible.builtin.service:
      name: nginx
      state: started