- name: variables from play level
  hosts: localhost
  vars:
    course: DevOps
    trainer: indra
    duration: 5 months
  tasks:
  - name: check variales
    ansible.builtin.debug:
      msg: "course is {{course}}, and trainer is {{trainer}} and duration is {{duration}}"  