- name: variables from play level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variales
    ansible.builtin.debug:
      msg: "course is {{course}}, and trainer is {{trainer}} and duration is {{duration}}"