- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: installing the packages
    ansible.builtin.package:
      name: {{item}}
      state: present
    loop:
    - git
    - postfix
    - mysql

      
    