- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: installing the packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: "git", state: "present"}
    - {name: "postfix", state: "absent"}
    - {name: "mysql", state: "absent"}
